# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29814dd93d017d3bb6a85b9c13457a9d80d43abd686514e0d70c9f1642a0a6bdd24e6d5b687105fac0daa7b9b75e8f1730b2efeef71c10c2df7e45fff3ae69e6

test:
  secret_key_base: 1e34fcb886a5ff7b7911e60b32e4f713311131e4d337a6c227ba3ba1bdb912f9ffa670743764d8dfe9fabf317654f1ddf3793109a55866149ac2d90dbc902d57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
